### ISSUE TITLE
unable to run in local host

### ISSUE THREAD

**Issue by shikhalakra22** [christiankyle-ching/roomfiles#1]
I followed  every steps you mentioned still i am unable to run in my local host . I got this error
![Screenshot from 2020-11-05 20-59-38](https://user-images.githubusercontent.com/48185254/98261143-232d3a00-1faa-11eb-9d3e-c3b70cc20606.png)

**Comment by christiankyle-ching** [comment]
I might have an error with the steps on the README.

Your error comes from incorrectly setup of django-googledrive-storage. (Documentation here: https://django-googledrive-storage.readthedocs.io/en/latest/)

After you created and obtained your private key in JSON from Google Developer Console, you have 2 options:

1. (Recommended) Add an environment variable to your local machine named `GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE_CONTENTS` and paste the content (not the file) of the JSON as the value.

2. (Not recommended, you could leak your private key on source control) Go to `/roomfiles/settings.py` and change the value of `GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE` from `None` to the path of the JSON file where it is located in your system.

**Comment by christiankyle-ching** [comment]
Closed for inactivity.

Duplicate of #2.
